version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps-      
      - run:
          name: Install frontend dependencies
          command: |
            npm run frontend:install
      - save_cache:
          key:  v1-npm-deps-   
          paths: 
            - node_modules  
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package.json" }}
            - v2-npm-deps-                      
      - run:
          name: Install backend dependencies
          command: |
            npm run backend:install
      - save_cache:
          key:  v2-npm-deps-   
          paths: 
            - node_modules    
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
workflows:
  main:                    # workflow label
    jobs:
      - build:  
          filters:
            branches:
               only:                
                  - main

