version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - restore_cache:
          keys:
            - my-frontend-cache{{ checksum "package.json" }}
            - v1-npm-deps-      
      - run:
          name: Install frontend dependencies
          command: npm run frontend:install
      - save_cache:
          key:  my-frontend-cache{{ checksum "package.json" }}     
          paths: 
            - node_modules 
            - Udagram/udagram-frontend             



      - restore_cache:
          keys:
            - my-backend-cache{{ checksum "package.json" }}
            - my-backend-cache                      
      - run:
          name: Install backend dependencies
          command: npm run backend:install
      - save_cache:
          key:  my-backend-cache{{ checksum "package.json" }}  
          paths: 
            - node_modules
            - Udagram/udagram-api  
              
      - run:
          name: Building Front-End 
          command: npm run frontend:build
      - run:
          name: Building Back-End 
          command: npm run backend:build            
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
workflows:
  main:                  
    jobs:
      - build:  
          filters:
            branches:
               only:                
                  - main

